spring:
  datasource:
    username: root
    password: migi987
    url: jdbc:mysql://localhost/sda_student_course_spring?serverTimezone=Europe/Warsaw&createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
      format_sql: true
      use_sql_comments: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org:
      hibernate:
        SQL: debug
default:
  participants:
    limit: 5